services: 
  web:
    image: bphsdevops/simulador-do-caos:v2 
    ports:
      - 8080:3000
    restart: always 
    healthcheck:
    #  test: ["CMD","curl", "-f", "http://localhost:3000/health"]
    #  interval: 5s 
    #  retries: 2 
    #  start_period: 30s 
    #  timeout: 10s
      disable: true  
    cpuset: "6"
    memswap_limit: "1G"
    deploy: 
      resources: 
        limits: 
          cpus: "0.5"
          memory: "1G"   